# Worksheet 04

Name:  Sumatra K Dhimoyee
UID: U26967910

### Topics

- Distance & Similarity

### Distance & Similarity

#### Part 1

a) In the minkowski distance, describe what the parameters p and d are.

d = no. of dimensions (characteristics of the dataset),
p = parameterizes the distance function

b) In your own words describe the difference between the Euclidean distance and the Manhattan distance.

Euclidean distance is the diagonal distance between two points while Manhattan distance is the distance when you can only move up or down but not diagonally.

Consider A = (0, 0) and B = (1, 1). When:

- p = 1, d(A, B) = 2
- p = 2, d(A, B) = $\sqrt{2} = 1.41$
- p = 3, d(A, B) = $2^{1/3} = 1.26$
- p = 4, d(A, B) = $2^{1/4} = 1.19$

c) Describe what you think distance would look like when p is very large.

The distance will convergence towards zero but never become equal to zero.

d) Is the minkowski distance still a distance function when p < 1? Expain why / why not.

No. If there are 3 points A(0,0), B(1,0) and C(0,1), and p =0.5, then D(B,A) + D(A,C)=2 and D(B,C)=2^(1/0.5)=4. Thus D(B,C)>D(B,A)+D(A,C) which violates the triangle inequality of distance function

e) when would you use cosine similarity over the euclidan distance?

This is important when the direction matters more than magnitude.

f) what does the jaccard distance account for that the manhattan distance doesn't?

The jaccard distance accounts for degree of dissimilarity between two sets which Manhattan distance doesn't.

#### Part 2

Consider the following two sentences:

In [59]:
s1 = "hello my name is Alice"  
s2 = "hello my name is Bob"

using the union of words from both sentences, we can represent each sentence as a vector. Each element of the vector represents the presence or absence of the word at that index.

In this example, the union of words is ("hello", "my", "name", "is", "Alice", "Bob") so we can represent the above sentences as such:

In [60]:
v1 = [1,    1, 1,   1, 1,    0]
#     hello my name is Alice
v2 = [1,    1, 1,   1, 0, 1]
#     hello my name is    Bob

Programmatically, we can do the following:

In [61]:
corpus = [s1, s2]
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)

['Alice', 'is', 'hello', 'name', 'Bob', 'my']
[1, 1, 1, 1, 0, 1]


Let's add a new sentence to our corpus:

In [62]:
s3 = "hi my name is Claude"
corpus.append(s3)

a) What is the new union of words used to represent s1, s2, and s3?

In [63]:
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)

['Alice', 'is', 'hello', 'hi', 'Claude', 'name', 'Bob', 'my']


b) Represent s1, s2, and s3 as vectors as above, using this new set of words.

In [64]:
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)
v2 = [1 if x in s2 else 0 for x in all_words]
print(v2)
v3 = [1 if x in s3 else 0 for x in all_words]
print(v3)

[1, 1, 1, 0, 0, 1, 0, 1]
[0, 1, 1, 0, 0, 1, 1, 1]
[0, 1, 0, 1, 1, 1, 0, 1]


c) Write a function that computes the manhattan distance between two vectors. Which pair of vectors are the most similar under that distance function?

In [65]:
def minkowski(x, y, p):
    if len(x) != len(y):
        raise RuntimeError ("x and u should be same dimension")
    res = 0
    for i in range(len(x)):
        res += abs(x[i]-y[i]) **p
    return res ** (1/p)

print(minkowski([0,0], [1, 1], 2)) # euclidan distance
print(minkowski([0,0], [1, 1], 1)) # manhattan distance

print("manhattan distance between v1 and v2:",minkowski(v1, v2, 1))
print("manhattan distance between v1 and v3:",minkowski(v1, v3, 1))
print("manhattan distance between v1 and v2:",minkowski(v2, v3, 1))
print("Comment: v1 and v2 are most similar under the distance function")

1.4142135623730951
2.0
manhattan distance between v1 and v2: 2.0
manhattan distance between v1 and v3: 4.0
manhattan distance between v1 and v2: 4.0
Comment: v1 and v2 are most similar under the distance function


d) Create a matrix of all these vectors (row major) and add the following sentences in vector form:

- "hi Alice"
- "hello Claude"
- "Bob my name is Claude"
- "hi Claude my name is Alice"
- "hello Bob"

In [66]:
import numpy as np
sr1="hi Alice"
sr2="hello Claude"
sr3="Bob my name is Claude"
sr4="hi Claude my name is Alice"
sr5="hello Bob"

word_list=["hi", "hello", "Bob", "Claude", "Alice", "my", "name", "is"]

def create_vector(sr):
    words = sr.split()
    v = [1 if word in words else 0 for word in word_list]
    return v

vectors = [create_vector(sr) for sr in [sr1, sr2, sr3, sr4, sr5]]
matrix = np.array(vectors)
print(matrix)

[[1 0 0 0 1 0 0 0]
 [0 1 0 1 0 0 0 0]
 [0 0 1 1 0 1 1 1]
 [1 0 0 1 1 1 1 1]
 [0 1 1 0 0 0 0 0]]


e) How many rows and columns does this matrix have?

In [67]:
print("column=8 (representing the number of words)")
print("rows=5 (representing the number of strings)")

column=8 (representing the number of words)
rows=5 (representing the number of strings)


f) When using the Manhattan distance, which two sentences are the most similar?

In [71]:
def distance_matrix(matrix, p):
    num_vectors = matrix.shape[0]
    distances = np.zeros((num_vectors, num_vectors))
    
    for i in range(num_vectors):
        for j in range(i + 1, num_vectors):
            dist = minkowski(matrix[i], matrix[j], p)
            distances[i, j] = dist
            distances[j, i] = dist
    
    return distances

distances = distance_matrix(matrix, 1)

# Print the distance matrix
print("Distance Matrix:")
print(distances)
print("Comments: Sentences 2 and 5 has highest level of similarties based on Manhattan distance")

Distance Matrix:
[[0. 4. 7. 4. 4.]
 [4. 0. 5. 6. 2.]
 [7. 5. 0. 3. 5.]
 [4. 6. 3. 0. 8.]
 [4. 2. 5. 8. 0.]]
Comments: Sentences 2 and 5 has highest level of similarties


In [69]:
def manhattan_distance(x, y):
    if len(x) != len(y):
        raise RuntimeError("x and y should be of the same length")
    return sum(abs(a - b) for a, b in zip(x, y))

# Define the strings
sr1 = "hi Alice"
sr2 = "hello Claude"
sr3 = "Bob my name is Claude"
sr4 = "hi Claude my name is Alice"
sr5 = "hello Bob"

# Tokenize strings into vectors
vocabulary = ["hi", "hello", "Alice", "Bob", "Claude", "my", "name", "is"]
vectors = [[1 if word in string.split() else 0 for word in vocabulary] for string in [sr1, sr2, sr3, sr4, sr5]]

# Calculate Manhattan distance between each pair of vectors
distances = {}
for i in range(len(vectors)):
    for j in range(i + 1, len(vectors)):
        distances[(i+1, j+1)] = manhattan_distance(vectors[i], vectors[j])

# Find the pair with the smallest Manhattan distance
closest_pair = min(distances, key=distances.get)

# Print the result
print("Strings with the most similarity (based on Manhattan distance):")
print("String", closest_pair[0], "and String", closest_pair[1], "with distance:", distances[closest_pair])

Strings with the most similarity (based on Manhattan distance):
String 2 and String 5 with distance: 2


#### Part 3 Challenge

Given a set of graphs $\mathcal{G}$, each graph $G \in \mathcal{G}$ is defined over the same set of nodes $V$. The graphs are represented by their adjacency matrices, which are 2D arrays where each element indicates whether a pair of nodes is connected by an edge.

Your task is to compute the pairwise distances between these graphs based on a specific distance metric. The distance $d(G, G')$ between two graphs $G = (V, E)$ and $G' = (V, E')$ is defined as the sum of the number of edges in $G$ but not in $G'$, and the number of edges in $G'$ but not in $G$. Mathematically, this can be expressed as:

$$
d(G, G') = |E \setminus E'| + |E' \setminus E|.
$$

##### Requirements:
1. **Input**: Should take a list of 2D numpy arrays as input. Each array represents the adjacency matrix of a graph.

2. **Output**: Should output a pairwise distance matrix. If there are $n$ graphs in the input list, the output should be an $n \times n$ matrix where the entry at position $(i, j)$ represents the distance between the $i^{th}$ and $j^{th}$ graph.

In [49]:
import numpy as np

def pairwise_distance(adj_matrices):
    num_graphs = len(adj_matrices)
    distances = np.zeros((num_graphs, num_graphs))

    for i in range(num_graphs):
        for j in range(i + 1, num_graphs):
            exclusive_edges = np.sum(adj_matrices[i]) + np.sum(adj_matrices[j]) - 2 * np.sum(np.logical_and(adj_matrices[i], adj_matrices[j]))
            distances[i, j] = exclusive_edges
            distances[j, i] = exclusive_edges

    return distances

adj_matrix1 = np.array([[0, 1, 1], [1, 0, 0], [1, 0, 0]])
adj_matrix2 = np.array([[0, 1, 0], [1, 0, 1], [0, 1, 0]])
adj_matrix3 = np.array([[0, 0, 1], [0, 0, 1], [1, 1, 0]])


adj_matrices = [adj_matrix1, adj_matrix2, adj_matrix3]

pairwise_distances = pairwise_distance(adj_matrices)

print("Pairwise Distance Matrix:")
print(pairwise_distances)

Pairwise Distance Matrix:
[[0. 4. 4.]
 [4. 0. 4.]
 [4. 4. 0.]]
